<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxnufAx\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxnufAx/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNxnufAx.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNxnufAx\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerNxnufAx\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'NxnufAx',
    'container.build_id' => 'd6dbb499',
    'container.build_time' => 1650544658,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxnufAx');
