<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZruhaZG\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZruhaZG/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZruhaZG.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZruhaZG\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerZruhaZG\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'ZruhaZG',
    'container.build_id' => '8fef0e7f',
    'container.build_time' => 1651154740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZruhaZG');
