<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0dOZpYZ\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0dOZpYZ/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/Container0dOZpYZ.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\Container0dOZpYZ\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \Container0dOZpYZ\Shopware_Core_KernelProdContainer([
    'container.build_hash' => '0dOZpYZ',
    'container.build_id' => 'f1007d1a',
    'container.build_time' => 1650541507,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0dOZpYZ');
