<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ4igkr7\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ4igkr7/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJ4igkr7.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJ4igkr7\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerJ4igkr7\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'J4igkr7',
    'container.build_id' => '24660330',
    'container.build_time' => 1651154718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ4igkr7');
