<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCrw1Xw\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCrw1Xw/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZCrw1Xw.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZCrw1Xw\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerZCrw1Xw\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'ZCrw1Xw',
    'container.build_id' => '07eda67e',
    'container.build_time' => 1650542968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCrw1Xw');
