<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpA8ZRP\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpA8ZRP/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZpA8ZRP.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZpA8ZRP\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerZpA8ZRP\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'ZpA8ZRP',
    'container.build_id' => '5f6465f9',
    'container.build_time' => 1650542832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpA8ZRP');
